"""Add cascade delete to ProductImage

Revision ID: 1042efd63e5d
Revises: 9628c54b3d73
Create Date: 2024-08-16 11:21:49.858714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1042efd63e5d'
down_revision = '9628c54b3d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductImage', schema=None) as batch_op:
        batch_op.drop_constraint('ProductImage_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductImage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ProductImage_product_id_fkey', 'Products', ['product_id'], ['id'])

    # ### end Alembic commands ###
