"""Created zone model

Revision ID: 45357a18ae70
Revises: c192ab7c4f62
Create Date: 2024-08-13 13:10:53.037211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45357a18ae70'
down_revision = 'c192ab7c4f62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Zone',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['warehouse_id'], ['Warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Zone')
    # ### end Alembic commands ###
