"""updated purchase order models

Revision ID: 54e505b79b50
Revises: 924adcb35606
Create Date: 2024-08-23 09:49:23.845026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54e505b79b50'
down_revision = '924adcb35606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PurchaseOrder',
    sa.Column('purchase_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('invoice', sa.String(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PurchaseOrderProducts',
    sa.Column('case_quantity', sa.Integer(), nullable=False),
    sa.Column('total_pieces', sa.Integer(), nullable=True),
    sa.Column('batch_number', sa.String(length=100), nullable=True),
    sa.Column('per_piece_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('case_size_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_size_id'], ['ProductCase.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['PurchaseOrder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('VendorPayments',
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('due_amount', sa.Float(), nullable=True),
    sa.Column('purchase_order_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['PurchaseOrder.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PurchaseOrderProductUnloadHistory',
    sa.Column('unload_stock', sa.Integer(), nullable=True),
    sa.Column('purchase_order_product_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_order_product_id'], ['PurchaseOrderProducts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PurchaseOrderProductUnloadHistory')
    op.drop_table('VendorPayments')
    op.drop_table('PurchaseOrderProducts')
    op.drop_table('PurchaseOrder')
    # ### end Alembic commands ###
