"""updated customers models

Revision ID: 924adcb35606
Revises: e844d2a4213e
Create Date: 2024-08-22 12:24:40.435629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924adcb35606'
down_revision = 'e844d2a4213e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
