"""reverted changes of  product image model

Revision ID: 9628c54b3d73
Revises: 11e56bb14185
Create Date: 2024-08-16 11:18:49.405873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9628c54b3d73'
down_revision = '11e56bb14185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductImage', schema=None) as batch_op:
        batch_op.drop_constraint('ProductImage_product_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'Products', ['product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ProductImage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('ProductImage_product_id_fkey', 'Products', ['product_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
