"""added stock models

Revision ID: aa28f0aeea6d
Revises: 164b6ce12678
Create Date: 2024-08-21 12:49:59.124619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa28f0aeea6d'
down_revision = '164b6ce12678'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('total_stock', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['Warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_history',
    sa.Column('no_of_case', sa.Integer(), nullable=True),
    sa.Column('manufacture_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('affected_stock', sa.Integer(), nullable=True),
    sa.Column('before_stock', sa.Integer(), nullable=True),
    sa.Column('per_piece_price', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('locked_quantity', sa.Integer(), nullable=True),
    sa.Column('load_quantity', sa.Integer(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('removed_at', sa.Date(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_case_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.Column('warehouse_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by_id'], ['User.id'], ),
    sa.ForeignKeyConstraint(['product_case_id'], ['ProductCase.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['Vendor.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['Warehouse.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['Zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_history')
    op.drop_table('stock')
    # ### end Alembic commands ###
