"""updated barcode model added str for code_url

Revision ID: b4b6e0bc6da0
Revises: 0d1de578ee1d
Create Date: 2024-08-20 09:49:04.046401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b4b6e0bc6da0'
down_revision = '0d1de578ee1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Barcode', schema=None) as batch_op:
        batch_op.alter_column('code_url',
               existing_type=postgresql.BYTEA(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Barcode', schema=None) as batch_op:
        batch_op.alter_column('code_url',
               existing_type=sa.String(length=255),
               type_=postgresql.BYTEA(),
               nullable=False)

    # ### end Alembic commands ###
