"""updated user model removed unique from email

Revision ID: bb910735d7e2
Revises: e6ca9fefdd7e
Create Date: 2024-08-12 16:52:23.512074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb910735d7e2'
down_revision = 'e6ca9fefdd7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_constraint('User_email_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.create_unique_constraint('User_email_key', ['email'])

    # ### end Alembic commands ###
